all:
	$(MAKE) -C stdlib
	$(MAKE) -C hello
	$(MAKE) -C blank
	$(MAKE) -C syscall
	$(MAKE) -C elf

clean:
	$(MAKE) -C stdlib clean
	$(MAKE) -C hello clean
	$(MAKE) -C blank clean
	$(MAKE) -C syscall clean
	$(MAKE) -C elf clean